---
#
# Ansible managed
#
repository:
  description: Install common CA certificates on your system.
  homepage: https://robertdebock.nl/
  topics: cacertificates, ca, ssl, certificates, security, ansible, molecule, tox, playbook
